const songs = [
  {
    id: 0,
    title: 'mama boy',
    artist: 'amme',
    avatar: ' ../assets/images/01.jpg',
    mp3: '../assets/music/01.mp3',
  },
  {
    id: 1,
    title: 'sài gòn hôm nay mưa',
    artist: 'JSOL, Hoàng Duyên',
    avatar: '../assets/images/saigonhomnaymua.jpg',
    mp3: '../assets/music/SaiGonHomNayMua.mp3',
  },
  {
    id: 2,
    title: 'vaicaunoicokhiennguoithaydoi',
    artist: 'GREY D, tlinh',
    avatar: '../assets/images/vaicaunoicokhiennguoithaydoi.jpg',
    mp3: '../assets/music/vaicaunoicokhiennguoithaydoi.mp3',
  },
  {
    id: 3,
    title: 'Waiting For You',
    artist: 'MONO, Onionn',
    avatar: '../assets/images/WaitingForYou.jpg',
    mp3: '../assets/music/WaitingForYou.mp3',
  },
  {
    id: 4,
    title: 'Em Là',
    artist: 'MONO, Onionn',
    avatar: '../assets/images/WaitingForYou.jpg',
    mp3: '../assets/music/EmLa.mp3',
  },
  {
    id: 5,
    title: 'Xích Thêm Chút Nữa',
    artist: 'GREY D, tlinh',
    avatar: '../assets/images/xichthemchutnua.jpg',
    mp3: '../assets/music/xichthemchutnua.mp3',
  },
  {
    id: 6,
    title: 'vì mẹ anh bắt chia tay',
    artist: 'miu lê, karik',
    avatar: '../assets/images/02.jpg',
    mp3: '../assets/music/02.mp3',
  },
  {
    id: 7,
    title: 'Tháng Năm',
    artist: 'Soobin Hoàng Sơn, SlimV',
    avatar: '../assets/images/thangnam.jpg',
    mp3: '../assets/music/ThangNam.mp3',
  },
  {
    id: 8,
    title: 'Xin Đừng Nhấc Máy',
    artist: 'Han Sara, T.R.I',
    avatar: '../assets/images/xindungnhacmay.jpg',
    mp3: '../assets/music/XinDungNhacMay.mp3',
  },
  {
    id: 9,
    title: 'matchanah',
    artist: 'híu, bâu',
    avatar: '../assets/images/07.jpg',
    mp3: '../assets/music/07.mp3',
  },
  {
    id: 10,
    title: 'QUERRY ',
    artist: 'QNT, TRUNG TRẦN, RPT MCK',
    avatar: '../assets/images/05.jpg',
    mp3: '../assets/music/05.mp3',
  },
  {
    id: 11,
    title: 'gác lại âu lo',
    artist: 'dalab, miu lê',
    avatar: '../assets/images/06.jpg',
    mp3: '../assets/music/06.mp3',
  },
  {
    id: 12,
    title: 'lời đường mật',
    artist: 'lyly, hiếu thứ hai',
    avatar: '../assets/images/08.jpg',
    mp3: '../assets/music/08.mp3',
  },
  {
    id: 13,
    title: 'cô gái vàng',
    artist: 'huyr, tùng viu',
    avatar: '../assets/images/09.jpg',
    mp3: '../assets/music/09.mp3',
  },
  {
    id: 14,
    title: 'cho mình em',
    artist: 'đen, binz',
    avatar: '../assets/images/10.jpg',
    mp3: '../assets/music/10.mp3',
  },
  {
    id: 15,
    title: 'Shay Nắnggg',
    artist: 'amme, obito',
    avatar: '../assets/images/03.jpg',
    mp3: '../assets/music/03.mp3',
  },
  {
    id: 16,
    title: 'chạy khỏi thế giới này',
    artist: 'Da LAB, Phương Ly',
    avatar: '../assets/images/04.jpg',
    mp3: '../assets/music/04.mp3',
  },
];

export default songs;
