export const ACCOUNTS = [
  {
    id: 1,
    username: 'user1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user1@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 2,
    username: 'user2',
    fullname: 'Tuyen',
    address: 'HCM City',
    email: 'user2@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 3,
    username: 'user3',
    fullname: 'Thao',
    address: 'HCM City',
    email: 'user3@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 4,
    username: 'user4',
    fullname: 'Kim Anh',
    address: 'HCM City',
    email: 'user4@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 5,
    username: 'user5',
    fullname: 'Nhu',
    address: 'HCM City',
    email: 'user5@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 6,
    username: 'user6',
    fullname: 'Huong',
    address: 'HCM City',
    email: 'user6@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 7,
    username: 'admin1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin1@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 8,
    username: 'user8',
    fullname: 'Hoang 8',
    address: 'HCM City',
    email: 'user8@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 9,
    username: 'user9',
    fullname: 'Hoang 9',
    address: 'HCM City',
    email: 'user9@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 10,
    username: 'user10',
    fullname: 'Hoang 10',
    address: 'HCM City',
    email: 'user10@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 11,
    username: 'user11',
    fullname: 'Hoang 1',
    address: 'HCM City',
    email: 'user11@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 12,
    username: 'admin2',
    fullname: 'Hoang 12',
    address: 'HCM City',
    email: 'admin2@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 13,
    username: 'admin3',
    fullname: 'Hoang 13',
    address: 'HCM City',
    email: 'admin3@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 14,
    username: 'user14',
    fullname: 'Hoang 14',
    address: 'HCM City',
    email: 'user14@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 15,
    username: 'user15',
    fullname: 'My',
    address: 'HCM City',
    email: 'user15@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 16,
    username: 'user16',
    fullname: 'Thang',
    address: 'HCM City',
    email: 'user16@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 17,
    username: 'user17',
    fullname: 'Hong',
    address: 'HCM City',
    email: 'user17@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 18,
    username: 'user18',
    fullname: 'Linh',
    address: 'HCM City',
    email: 'user18@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 19,
    username: 'user19',
    fullname: 'Hieu',
    address: 'HCM City',
    email: 'user19@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 20,
    username: 'admin4',
    fullname: 'Duyen',
    address: 'HCM City',
    email: 'admin4@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },

  {
    id: 21,
    username: 'user1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user1@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 22,
    username: 'user2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user2@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 23,
    username: 'user3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user3@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 24,
    username: 'user4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user4@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 25,
    username: 'user5',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user5@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 26,
    username: 'user6',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user6@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 27,
    username: 'admin1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin1@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 28,
    username: 'user8',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user8@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 29,
    username: 'user9',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user9@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 30,
    username: 'user10',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user10@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 31,
    username: 'user11',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user11@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 32,
    username: 'admin2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin2@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 33,
    username: 'admin3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin3@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 34,
    username: 'user14',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user14@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 35,
    username: 'user15',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user15@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 36,
    username: 'user16',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user16@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 37,
    username: 'user17',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user17@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 38,
    username: 'user18',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user18@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 39,
    username: 'user19',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user19@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 40,
    username: 'admin4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin4@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },

  {
    id: 41,
    username: 'user1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user1@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 42,
    username: 'user2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user2@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 43,
    username: 'user3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user3@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 44,
    username: 'user4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user4@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 45,
    username: 'user5',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user5@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 46,
    username: 'user6',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user6@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 47,
    username: 'admin1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin1@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 48,
    username: 'user8',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user8@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 49,
    username: 'user9',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user9@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 50,
    username: 'user10',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user10@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 51,
    username: 'user11',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user11@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 52,
    username: 'admin2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin2@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 53,
    username: 'admin3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin3@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 54,
    username: 'user14',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user14@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 55,
    username: 'user15',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user15@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 56,
    username: 'user16',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user16@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 57,
    username: 'user17',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user17@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 58,
    username: 'user18',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user18@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 59,
    username: 'user19',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user19@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 60,
    username: 'admin4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin4@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },

  {
    id: 61,
    username: 'user1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user1@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 62,
    username: 'user2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user2@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 63,
    username: 'user3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user3@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 64,
    username: 'user4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user4@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 65,
    username: 'user5',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user5@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 66,
    username: 'user6',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user6@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 67,
    username: 'admin1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin1@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 68,
    username: 'user8',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user8@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 69,
    username: 'user9',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user9@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 70,
    username: 'user10',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user10@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 71,
    username: 'user11',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user11@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 72,
    username: 'admin2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin2@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 73,
    username: 'admin3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin3@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 74,
    username: 'user14',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user14@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 75,
    username: 'user15',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user15@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 76,
    username: 'user16',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user16@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 77,
    username: 'user17',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user17@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 78,
    username: 'user18',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user18@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 79,
    username: 'user19',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user19@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 80,
    username: 'admin4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin4@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },

  {
    id: 81,
    username: 'user1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user1@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 82,
    username: 'user2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user2@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 83,
    username: 'user3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user3@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 84,
    username: 'user4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user4@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 85,
    username: 'user5',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user5@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 86,
    username: 'user6',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user6@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 87,
    username: 'admin1',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin1@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 88,
    username: 'user8',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user8@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 89,
    username: 'user9',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user9@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 90,
    username: 'user10',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user10@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 91,
    username: 'user11',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user11@gmail.com',
    phone: '0939123123',
    status: 3,
    role: 1,
  },
  {
    id: 92,
    username: 'admin2',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin2@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 93,
    username: 'admin3',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin3@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
  {
    id: 94,
    username: 'user14',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user14@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 95,
    username: 'user15',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user15@gmail.com',
    phone: '0939123123',
    status: 0,
    role: 1,
  },
  {
    id: 96,
    username: 'user16',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user16@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 97,
    username: 'user17',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user17@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 98,
    username: 'user18',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user18@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 99,
    username: 'user19',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'user19@gmail.com',
    phone: '0939123123',
    status: 2,
    role: 1,
  },
  {
    id: 100,
    username: 'admin4',
    fullname: 'Hoang',
    address: 'HCM City',
    email: 'admin4@gmail.com',
    phone: '0939321123',
    status: 2,
    role: 0,
  },
];
